defaults:
  - base

model:
  type: coord
  encoder_name: tu-timm/tf_efficientnet_b7.ns_jft_in1k
  encoder_weights: imagenet
  decoder_name: unet
  use_coord_conv: true
  coord_decoder_depth: 5
  loss_weight: 10

training:
  batch_size: 4
  num_epochs: 50
  gradient_accumulation_steps: 1
  amp: true

coord:
  offset: 416
