defaults:
  - base

model:
  type: lead
  encoder_name: tu-timm/tf_efficientnet_b6.ns_jft_in1k
  encoder_weights: imagenet
  fusion_type: shared_conv2d
  fusion_levels: [1, 2, 3, 4]
  num_leads: 4
  loss_weight: 10

training:
  batch_size: 4
  num_epochs: 50
  gradient_accumulation_steps: 1
  amp: true

lead:
  window_size: 240
