defaults:
  - base

zero_mv: [287.5, 571.5, 855.5, 1115.5]

model:
  type: whole
  encoder_name: tu-timm/tf_efficientnet_b0.ns_jft_in1k
  encoder_weights: imagenet
  whole_decoder_depth: 4
  loss_weight: 20
  enable_checkpointing: True

training:
  batch_size: 4
  num_epochs: 50
  gradient_accumulation_steps: 1

whole:
  offset: 416
